version: '3.8'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:5.7.42
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - "${DB_LOCAL_PORT}:${DB_DOCKER_PORT}"
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  nestjs-app:
    container_name: nestjs-app
    build: .
    env_file: ./.env
    ports:
      - "${APP_LOCAL_PORT}:${APP_DOCKER_PORT}"
    environment:
      - DB_HOST=mysql-db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_NAME
      - DB_PORT=$DB_DOCKER_PORT
    volumes:
      - ./src:/app/src

volumes:
  mysql-volume:
